package uk.gov.hmcts.reform.cmc.performance.legalprocesses

import io.gatling.core.Predef._
import io.gatling.core.structure.ChainBuilder
import io.gatling.http.Predef._
import uk.gov.hmcts.reform.cmc.performance.legalprocesses.LegalLoginPage.thinktime
import uk.gov.hmcts.reform.cmc.performance.simulations.checks.CsrfCheck.{csrfParameter, csrfTemplate}
import uk.gov.hmcts.reform.cmc.performance.simulations.checks.CurrentPageCheck.currentPageTemplate
import uk.gov.hmcts.reform.cmc.performance.simulations.checks.{CsrfCheck, CurrentPageCheck}

object DefendantDetails {

  def run(implicit postHeaders: Map[String, String]): ChainBuilder = {
      exec(http("CLR01_0150_DefendantType")
        .post(currentPageTemplate)
        .formParam(csrfParameter, csrfTemplate)
        .formParam("type", "ORGANISATION")
        .formParam("organisation", "abc defandant org")
        .formParam("companyHouseNumber","FX12345")
        .formParam("soleTraderName", "")
        .formParam("businessName", "")
        .formParam("fullName", "")
        .check(status.in(200,201,204))
        .check(CurrentPageCheck.save)
        .check(CsrfCheck.save)
      )
        .pause(thinktime)
      .exec(http("CLR01_0160_Def_Org_Addr")
        .post(currentPageTemplate)
        .formParam(csrfParameter, csrfTemplate)
        .formParam("line1", "8")
        .formParam("line2", "Hibernia Gardens")
        .formParam("city", "Hounslow")
        .formParam("postcode", "TW3 3SD")
        .check(status.in(200,201,204))
        .check(CurrentPageCheck.save)
        .check(CsrfCheck.save)
      )
        .pause(thinktime)

      .exec(http("CLR01_0170_Def_Rep")
        .post(currentPageTemplate)
        .formParam(csrfParameter, csrfTemplate)
        .formParam("isDefendantRepresented", "YES")
        .formParam("organisationName", "deflegalrep123")
        .check(status.in(200,201,204))
        .check(CurrentPageCheck.save)
        .check(CsrfCheck.save)
      )
        .pause(thinktime)

        .exec(http("CLR01_0180_Def_Rep_Address")
          .post(currentPageTemplate)
          .formParam(csrfParameter, csrfTemplate)
          .formParam("line1", "12")
          .formParam("line2", "Hibernia Gardens")
          .formParam("city", "Hounslow")
          .formParam("postcode", "TW3 3SD")
          .check(status.in(200,201,204))
          .check(CurrentPageCheck.save)
          .check(CsrfCheck.save)
        )
        .pause(thinktime)
        .exec(http("CLR01_0190_Add_More_Defs")
          .post(currentPageTemplate)
          .formParam(csrfParameter, csrfTemplate)
          .formParam("isAddDefendant", "YES")
          .check(status.in(200,201,204))
          .check(CurrentPageCheck.save)
          .check(CsrfCheck.save)
          //.check(regex("Is it a personal injury claim?"))
        )
        .pause(thinktime)

        .exec(http("CLR01_0200_addnl_Def_Type")
          .post(currentPageTemplate)
          .formParam(csrfParameter, csrfTemplate)
          .formParam("organisation", "")
          .formParam("companyHouseNumber", "")
          .formParam("type", "SOLE_TRADER")
          .formParam("soleTraderName", "mr dddd aaaaa")
          .formParam("businessName", "sss ltd")
          .formParam("fullName", "")
          .check(status.in(200,201,204))
          .check(CurrentPageCheck.save)
          .check(CsrfCheck.save)
        )
        .pause(thinktime)
        .exec(http("CLR01_0210_Addnl_Def_Addr")
          .post(currentPageTemplate)
          .formParam(csrfParameter, csrfTemplate)
          .formParam("line1", "26")
          .formParam("line2", "Hibernia Gardens")
          .formParam("city", "Hounslow")
          .formParam("postcode", "TW3 3SD")
          .check(status.in(200,201,204))
          .check(CurrentPageCheck.save)
          .check(CsrfCheck.save)
        )
        .pause(thinktime)
        .exec(http("CLR01_0220_IsMoreDef")
          .post(currentPageTemplate)
          .formParam(csrfParameter, csrfTemplate)
          .formParam("isDefendantRepresented", "YES")
          .formParam("organisationName", "asasasa org")
          .check(status.in(200,201,204))
          .check(CurrentPageCheck.save)
          .check(CsrfCheck.save)
        )
        .pause(thinktime)
        .exec(http("CLR01_0230_AddnlDef_Addr")
          .post(currentPageTemplate)
          .formParam(csrfParameter, csrfTemplate)
          .formParam("line1", "19")
          .formParam("line2", "Hibernia Gardens")
          .formParam("city", "Hounslow")
          .formParam("postcode", "TW3 3SD")
          .check(status.in(200,201,204))
          .check(CurrentPageCheck.save)
          .check(CsrfCheck.save)
        )
        .pause(thinktime)

     .exec(http("CLR01_0240_IsMoreDefendants")
        .post(currentPageTemplate)
        .formParam(csrfParameter, csrfTemplate)
        .formParam("isAddDefendant", "NO")
       .check(status.in(200,201,204))
        .check(CurrentPageCheck.save)
        .check(CsrfCheck.save)
        .check(regex("Is it a personal injury claim?"))
      )
        .pause(thinktime)


  }

}
